# Generated by Django 6.0.3 on 2026-04-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('reviewed', 'Reviewed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
