# Generated by Django 6.0.3 on 2026-04-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_medicalreport_status_medicalreport_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='report_image',
            field=models.ImageField(blank=True, help_text='Upload test results, X-rays, or other medical images', null=True, upload_to='medical_reports/'),
        ),
    ]
