# Generated by Django 6.0.3 on 2026-04-06 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hospital_profile_hospital'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='accounts.hospital'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
